# Generated by Django 4.1.4 on 2022-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echipe',
            fields=[
                ('nume', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tara', models.CharField(max_length=40)),
                ('antrenor', models.CharField(max_length=50)),
                ('premii', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
