# Generated by Django 4.1.4 on 2022-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0002_echipe_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1', models.CharField(max_length=50)),
                ('e2', models.CharField(max_length=50)),
                ('g1', models.PositiveIntegerField(default=0)),
                ('g2', models.PositiveIntegerField(default=0)),
                ('data', models.DateField()),
                ('loc', models.CharField(max_length=100)),
            ],
        ),
    ]
